"""Remove meeting model

Revision ID: 87c1996beb3e
Revises: 
Create Date: 2021-02-15 12:28:54.538576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c1996beb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('date_end', sa.DATE(), nullable=False),
    sa.Column('time_start', sa.TIME(), nullable=False),
    sa.Column('time_end', sa.TIME(), nullable=False),
    sa.Column('place', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
